In [1]:
import pandas as pd

data = pd.read_csv("./hoodedjacket_e.csv", encoding="CP949")

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14636 entries, 0 to 14635
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             14636 non-null  int64
 1   Category               14636 non-null  object
 2   Detailed Category      14636 non-null  object
 3   Brand Name(KOR)        14636 non-null  object
 4   Brand Name(ENG)        14636 non-null  object
 5   Product Code(MUSINSA)  14636 non-null  object
 6   Sex                    14636 non-null  object
 7   Size_List              14636 non-null  object
 8   Customer Sex(Stat)     14636 non-null  object
 9   Customer Age(Stat)     14636 non-null  object
 10  Price                  14636 non-null  object
 11  Reviewer_Height        14636 non-null  object
 12  Reviewer_Weight        14636 non-null  object
 13  Reviewer_Sex           14636 non-null  object
 14  Reviewer_Bought_Size   14636 non-null  object
 15  Reviewer_Size_Review   14636 non-null  object
 16  Age_int                14636 non-null  int64
 17  Price_int              14636 non-null  int64
 18  Height                 14636 non-null  int64
 19  Weight                 14636 non-null  int64
 20  Size_detail            14636 non-null  object
 21  Upper                  14636 non-null  float64
 22  Shoulder               14636 non-null  float64
 23  Chest                  14636 non-null  float64
 24  Arm                    14636 non-null  float64
dtypes: float64(4), int64(5), object(16)
memory usage: 2.8+ MB

In [3]:
data.head()

,Unnamed: 0,Category,Detailed Category,Brand Name(KOR),Brand Name(ENG),Product Code(MUSINSA),Sex,Size_List,Customer Sex(Stat),Customer Age(Stat),...,Reviewer_Size_Review,Age_int,Price_int,Height,Weight,Size_detail,Upper,Shoulder,Chest,Arm
0,0,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,남,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,보통이에요,21,39900,170,60,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
1,1,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,남,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,보통이에요,21,39900,170,66,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
2,2,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,남,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,보통이에요,21,39900,165,64,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
3,3,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,남,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,보통이에요,21,39900,182,85,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
4,4,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,남,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,커요,21,39900,175,72,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0

In [4]:
def parseSex(sex):
    if sex == "남" or sex == "남성":
        return 0
    return 1

data['Sex'] = data['Sex'].apply(lambda x: parseSex(x))
data['Reviewer_Sex'] = data['Reviewer_Sex'].apply(lambda x: parseSex(x))

In [10]:
def parseReview(review):
    if review == "작아요":
        return 0
    elif review == '보통이에요':
        return 1
    else:
        return 2
    
data['Reviewer_Size_Review'] = data['Reviewer_Size_Review'].apply(lambda x: parseReview(x))

In [6]:
x = data.drop(['Reviewer_Size_Review', 'Reviewer_Bought_Size', 'Unnamed: 0', 'Reviewer_Bought_Size'], axis=1)
y = data.iloc[:, 4]

In [11]:
data.head()

,Unnamed: 0,Category,Detailed Category,Brand Name(KOR),Brand Name(ENG),Product Code(MUSINSA),Sex,Size_List,Customer Sex(Stat),Customer Age(Stat),...,Reviewer_Size_Review,Age_int,Price_int,Height,Weight,Size_detail,Upper,Shoulder,Chest,Arm
0,0,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,0,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,2,21,39900,170,60,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
1,1,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,0,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,2,21,39900,170,66,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
2,2,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,0,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,2,21,39900,165,64,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
3,3,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,0,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,2,21,39900,182,85,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0
4,4,아우터,후드 집업,멜란지 마스터,MELANGE MASTER,MUS_MMTS0003-MG,0,"[['S', '65', '46.5', '52', '61'], ['M', '67', ...",남성,19~23,...,2,21,39900,175,72,"['M', '67', '48.5', '54.5', '63']",67.0,48.5,54.5,63.0

In [7]:
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [9]:
knn_clf  = KNeighborsClassifier(n_neighbors=4)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=0)
dt_clf = DecisionTreeClassifier()
ada_clf = AdaBoostClassifier(n_estimators=100)

lr_final = LogisticRegression(C=10)

knn_clf.fit(X_train, Y_train)
rf_clf.fit(X_train , Y_train)
dt_clf.fit(X_train , Y_train)
ada_clf.fit(X_train, Y_train)

ValueError: could not convert string to float: '아우터'

In [ ]:
knn_pred = knn_clf.predict(X_test)
rf_pred = rf_clf.predict(X_test)
dt_pred = dt_clf.predict(X_test)
ada_pred = ada_clf.predict(X_test)

print('KNN 정확도: {0:.4f}'.format(accuracy_score(Y_test, knn_pred)))
print('랜덤 포레스트 정확도: {0:.4f}'.format(accuracy_score(Y_test, rf_pred)))
print('결정 트리 정확도: {0:.4f}'.format(accuracy_score(Y_test, dt_pred)))
print('에이다부스트 정확도: {0:.4f} :'.format(accuracy_score(Y_test, ada_pred)))

In [ ]:
# transpose를 이용해 행과 열의 위치 교환. 컬럼 레벨로 각 알고리즘의 예측 결과를 피처로 만듦. 
pred = np.array([knn_pred, rf_pred, dt_pred, ada_pred])
pred = np.transpose(pred)

lr_final.fit(pred, Y_test)
final = lr_final.predict(pred)

print('최종 메타 모델의 예측 정확도: {0:.4f}'.format(accuracy_score(Y_test , final)))

In [ ]:
print(pred)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , Y_train)
pred = rf_clf.predict(X_test)
accuracy = accuracy_score(Y_test , pred)
print(f'랜덤 포레스트 정확도: {accuracy:.4f}')

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators':[100],
    'max_depth' : [6, 8, 10, 12], 
    'min_samples_leaf' : [8, 12, 18 ],
    'min_samples_split' : [8, 16, 20]
}

In [ ]:
rf_clf = RandomForestClassifier(random_state=0, n_jobs=-1)
grid_cv = GridSearchCV(rf_clf , param_grid=params , cv=2, n_jobs=-1 )
grid_cv.fit(X_train , Y_train)

In [ ]:
print('최적 하이퍼 파라미터:\n', grid_cv.best_params_)
print(f'최고 예측 정확도: {grid_cv.best_score_:.4f}')

In [ ]:
rf_clf1 = RandomForestClassifier(n_estimators=300, max_depth=10, min_samples_leaf=8, \
                                 min_samples_split=8, random_state=0)
rf_clf1.fit(X_train , Y_train)
pred = rf_clf1.predict(X_test)
print(pred)
print(f'예측 정확도: {accuracy_score(Y_test , pred):.4f}')

In [ ]:
X_test.head()

In [ ]:
#SAMPLE 

sex = [0,0,0,0,0]
Reviewer_Sex = [0,0,0,0,0]
Height_int = [180,180,180,180,180]
Weight_int = [72,72,72,72,72,72]
Upper_int = [65,67,68.5,70,71.5]
Shoulder_int = [46.5,48.5,50,51.5,53]
Chest_int = [52,54.5,57,59.5,62]
Arm_int = [61, 63, 64,65,66]

test = pd.DataFrame(list(zip(sex,Reviewer_Sex,Height_int,Weight_int,Upper_int,Shoulder_int,Chest_int,Arm_int)),
                   columns=['sex','Reviewer_Sex','Height_int','Weight_int', 'Upper_int', 'Shoulder_int', 'Chest_int','Arm_int'])

In [ ]:
test.head()

In [ ]:
pred = rf_clf1.predict_proba(test)
print(pred)

In [ ]:
import joblib
joblib.dump(rf_clf1,'./rf_clf.pkl', compress=9)

In [ ]:
jean_data = pd.read_csv("./jeans_e.csv", encoding="CP949")